### ISSUE TITLE
The price for 2 x 2.0 GHz Cores (#112863) is not valid for location hou02

### ISSUE THREAD

**Issue by lcsmith02** [softlayer/softlayer-python#629] opened 2015-10-08 17:45 UTC
I am trying to order a virtual server with Windows and VCenter installed on it. Before placing the order I verify it, and I get the following error message:
The price for 2 x 2.0 GHz Cores (#112863) is not valid for location hou02

I have tried all the other datacenter locations, but I get the same error message. Could you tell me what's the cause?

**Comment by sudorandom** [comment] 2015-10-12 22:56
@lcsmith02 Hi, sorry for the delayed response. Is this still an issue? If so, is it possible to post code examples? This might be account specific, so be warned that you might be advised to create a support ticket if we cannot reproduce the issue here.

Ping for @underscorephil 's awareness

**Comment by underscorephil** [comment] 2015-10-14 21:55
@lcsmith02 can you send me the script you are working with? If needed, please use the email in my profile.

**Comment by mbenantar** [comment] 2015-11-12 19:29
@lcsmith02 I am running into same issue - have you been able to resolve - what did you do? Thanks

**Comment by mbenantar** [comment] 2015-11-12 19:30
This must be a recent change on the API service side

**Comment by sudorandom** [comment] 2015-11-20 00:26
Since this is apparently an API-side issue (and not client) I'm going to close this issue. This should be handled in support tickets unless there is a better place (@underscorephil might have a suggestion).

**Closed by sudorandom** 2015-11-20 00:26 UTC
