### ISSUE TITLE
SL cli error in printing summary of account

### ISSUE THREAD

**Issue by mbhavya** [softlayer/softlayer-python#1009] opened 2018-07-24 02:37 UTC
### Expected Behavior
Summary of softlayer account printed on terminal
### Actual Behavior
Stack trace of error is thrown
### Environment Information
Operating System: Fedora 28
softlayer-python version (`slcli --version`): 5.4.4

---------------
Stack trace
<pre>
$ slcli -C ~/.softlayer_312066 summary
An unexpected error has occured:
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.6/site-packages/SoftLayer/CLI/core.py", line 176, in main
    cli.main(**kwargs)
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.6/site-packages/SoftLayer/CLI/summary.py", line 44, in cli
    env.fout(table)
  File "/home/user/miniconda3/lib/python3.6/site-packages/SoftLayer/CLI/environment.py", line 56, in fout
    self.out(self.fmt(output), newline=newline)
  File "/home/user/miniconda3/lib/python3.6/site-packages/SoftLayer/CLI/environment.py", line 51, in fmt
    return formatting.format_output(output, fmt=self.format)
  File "/home/user/miniconda3/lib/python3.6/site-packages/SoftLayer/CLI/formatting.py", line 38, in format_output
    return str(format_prettytable(data))
  File "/home/user/miniconda3/lib/python3.6/site-packages/prettytable.py", line 237, in __str__
    return self.__unicode__()
  File "/home/user/miniconda3/lib/python3.6/site-packages/prettytable.py", line 243, in __unicode__
    return self.get_string()
  File "/home/user/miniconda3/lib/python3.6/site-packages/prettytable.py", line 984, in get_string
    rows = self._get_rows(options)
  File "/home/user/miniconda3/lib/python3.6/site-packages/prettytable.py", line 933, in _get_rows
    rows.sort(reverse=options["reversesort"], key=options["sort_key"])
TypeError: '<' not supported between instances of 'str' and 'NoneType'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
The following snippet should be able to reproduce the error
$ slcli --version
slcli (SoftLayer Command-line), version 5.4.4
</pre>

**Comment by acamacho82** [comment] 2018-07-26 22:10
I could reproduced it in the 5.4.4 version but it seems to be fixed in the newest version 5.5.0, I recommend you upgrade and try again
```
$ slcli summary
:............:..........:.................:.......:.........:............:
: datacenter : hardware : virtual_servers : vlans : subnets : public_ips :
:............:..........:.................:.......:.........:............:
:   ams01    :    23    :        22       :   11  :    36   :    384     :
:   ams03    :    1     :        4        :   7   :    8    :    211     :
:............:..........:.................:.......:.........:............:`
$ slcli --version
slcli (SoftLayer Command-line), version 5.5.0

```

**Closed** 2018-07-31 21:26 UTC
