### ISSUE TITLE
'slcli vs ready' fails

### ISSUE THREAD

**Issue by amolmanjure** [softlayer/softlayer-python#563] opened 2015-06-09 12:30 UTC
'slcli vs ready' fails on my Ubuntu 12.04 box. Here are my environment details and the error log.

$ python -V
Python 2.7.3

$ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
Django==1.6.5
GnuPGInterface==0.3.2
Magic-file-extensions==0.2
Mako==0.5.0
MarkupSafe==0.15
PIL==1.1.7
Paste==1.7.5.1
PyYAML==3.11
Pygments==1.4
RBTools==0.6.2
SOAPpy==0.12.0
SoftLayer==4.0.2
Unipath==1.0
VorSysUtils==1.0.0
WebOb==1.4
WebTest==2.0.16
apt-xapian-index==0.44
argparse==1.2.1
awscli==1.4.1
bcdoc==0.12.2
beautifulsoup4==4.3.2
boto==2.32.1
botocore==0.61.0
boxsdk==1.1.5
certifi==14.05.14
cffi==1.1.1
chardet==2.0.1
click==4.0
colorama==0.2.5
contextlib2==0.4.0
coverage==3.7.1
cryptography==0.9.1
decorator==3.4.0
devscripts==2.11.6ubuntu1.6
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
django-debug-toolbar==1.2.1
djangorestframework==2.3.14
docutils==0.12
ecdsa==0.11
enum34==1.0.4
filechunkio==1.6
fpconst==0.7.2
idna==2.0
ipaddress==1.0.7
jmespath==0.4.1
jq==0.1.3
jsonpatch==1.8
jsonpointer==1.4
lxml==2.3.2
mock==1.0.1
mongoengine==0.8.7
ndg-httpsclient==0.4.0
nose==1.3.3
paramiko==1.14.0
prettytable==0.7.2
pyOpenSSL==0.15.1
pyasn1==0.1.7
pycparser==2.13
pycrypto==2.4.1
pycurl==7.19.5
pymongo==2.7.2
python-apt==0.8.3ubuntu7.3
python-dateutil==2.2
python-debian==0.1.21ubuntu1
python-debianbts==1.10
python-ldap==2.4.16
pytz==2014.4
requests==2.6.0
robotframework==2.8.5
robotframework-httplibrary==0.4.2
robotframework-requests==0.3.7
robotframework-selenium2library==1.5.0
robotframework-sshlibrary==2.1.1
rsa==3.1.2
selenium==2.43.0
six==1.7.3
sqlparse==0.1.13
stevedore==0.15
unattended-upgrades==0.1
vboxapi==1.0
vcrpy==1.1.1
virtualenv==1.11.6
virtualenv-clone==0.2.5
virtualenvwrapper==4.3.1
waitress==0.8.9
web.py==0.37
wrapt==1.9.0
wsgiref==0.1.2
zenmap==6.40

$ slcli vs list
:.........:.............:................:..............:............:........:
:    id   :   hostname  :   primary_ip   :  backend_ip  : datacenter : action :
:.........:.............:................:..............:............:........:
: 9906117 : dsmtemplate : 198.11.221.124 : 10.91.123.79 :   sjc01    :   -    :
:.........:.............:................:..............:............:........:

$ slcli vs ready 9906117
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: cli() takes exactly 3 arguments (2 given)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

$ slcli vs ready dsmtemplate
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 180, in main
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: cli() takes exactly 3 arguments (2 given)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by underscorephil** [comment] 2015-06-12 15:56
Confirmed the same error in master branch

**Comment by sudorandom** [comment] 2015-06-12 15:59
@underscorephil Are you sue you've updated your master branch? This looks like a duplicate of #557. It should be fixed in master and go out on the next release. #562 is the last bug fix before a release will be done.

**Comment by amolmanjure** [comment] 2015-06-15 07:00
Works when I install the latest code from source. @sudorandom When is the next release due? I would like to stick to a pip install.

**Comment by sudorandom** [comment] 2015-06-15 22:26
@amolmanjure I just performed a release a few minutes ago

**Closed by sudorandom** 2015-06-15 22:26 UTC
Labels: Bug, CLI

**Comment by amolmanjure** [comment] 2015-06-16 06:37
@sudorandom Thanks. Works on 4.0.3.
