### ISSUE TITLE
FileStorageManager.order_file_volume does not work as expected

### ISSUE THREAD

**Issue by tianhw2006** [softlayer/softlayer-python#904] opened 2017-12-14 02:00 UTC
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Provision an Endurance file storage successfully

### Actual Behavior
while I run the following 
``` 
    client = SoftLayer.Client(username=sl_user, api_key=sl_api_key)
    filestorage_manager = SoftLayer.FileStorageManager(client)
    result = filestorage_manager.order_file_volume(
        storage_type='endurance',
        location='dal10',
        size=20,
        iops=None,
        tier_level=4,
        service_offering='enterprise'
        )
```
I saw the error
```
File "/Library/Python/2.7/site-packages/SoftLayer/managers/file.py", line 343, in order_file_volume
    snapshot_size, service_offering, 'file', hourly_billing_flag
  File "/Library/Python/2.7/site-packages/SoftLayer/managers/storage_utils.py", line 683, in prepare_volume_order_object
    find_price_by_category(package, order_category_code),
  File "/Library/Python/2.7/site-packages/SoftLayer/managers/storage_utils.py", line 125, in find_price_by_category
    % price_category)
ValueError: Could not find price with the category, storage_service_enterprise
```

### Environment Information
Operating System: Mas
softlayer-python version (`slcli --version`): 5.3.1

**Comment by tianhw2006** [comment] 2017-12-14 02:05
The same issue was reported in https://github.com/softlayer/softlayer-python/issues/903.  That issue was closed, but the problem is still existing.

Please have a look.

The workaround is to change to `if price['locationGroupId'] is not None` in storage_utils.py, such as in https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/storage_utils.py#L116.

**Comment by allmightyspiff** [comment] 2017-12-14 02:12
Thanks, I'll take a look.

**Comment by allmightyspiff** [comment] 2017-12-16 04:00
I haven't been able to reproduce this problem.

```
import SoftLayer
from pprint import pprint as pp
from SoftLayer.managers import storage_utils


client = SoftLayer.Client()
filestorage_manager = SoftLayer.FileStorageManager(client)

#result = filestorage_manager.order_file_volume(
#    storage_type='endurance',
#    location='dal10',
#    size=20,
#    iops=None,
#    tier_level=4,
#    service_offering='enterprise'
#    )
packages = storage_utils.get_package(filestorage_manager, 'storage_service_enterprise')
pp(packages)
```

If you run that code, you SHOULD get an output of all the storage prices. In that json data should be an object that looks like the following.

```json
{'attributes': [],
'capacity': '0',
'description': 'Endurance Storage',
'id': 5936,
'itemCategory': {'categoryCode': 'storage_service_enterprise',
                 'id': 394,
                 'name': 'Endurance',
                 'quantityLimit': 0,
                 'sortOrder': ''},
'itemTaxCategoryId': 166,
'keyName': 'CODENAME_PRIME_STORAGE_SERVICE',
'prices': [{'categories': [{'categoryCode': 'storage_service_enterprise',
                            'id': 394,
                            'name': 'Endurance',
                            'quantityLimit': 0,
                            'sortOrder': ''}],
            'currentPriceFlag': '',
            'id': 45058,
            'itemId': 5936,
            'laborFee': '0',
            'locationGroupId': '',
            'onSaleFlag': '',
            'oneTimeFee': '0',
            'quantity': '',
            'recurringFee': '0',
            'setupFee': '0',
            'sort': 10,
            'tierMinimumThreshold': ''}],
'softwareDescriptionId': '',
'units': 'N/A',
'upgradeItemId': ''},
```

Which is what this storage utility is looking for. Do you get the same data back? The reason we need to look for locationGroupId == '' instead of "not None" is because locationGroupId  is used to determine different prices for different regions. And only '' is the default location.

**Comment by allmightyspiff** [comment] 2018-04-12 20:44
Looks like this might be related to how rest and xml responses are returned. 

Using the XMLRPC endpoint, I get back `price['locationGroupId'] = ''`, using REST, I get back `price['locationGroupId'] = None`

`slcli image list` (line 45) also has this problem that I have seen. 

I'll try to get this fixed in the next minor release, hopefully by end of next week.

**Closed** 2018-05-22 20:51 UTC
Labels: Bug
