### ISSUE TITLE
VLAN detail function broken in 5.0

### ISSUE THREAD

**Issue by greyhoundforty** [softlayer/softlayer-python#713] opened 2016-04-01 15:37 UTC
### Expected Behavior
Obtaining details about a VLAN including additional subnets. This worked in pre-5.0 versions 

```
ryan@galileo ~ % slcli --version
slcli (SoftLayer Command-line), version 4.1.1

ryan@galileo ~ % slcli --format raw vlan detail 1072493
id              1072493
number          1318
datacenter      Houston 2
primary_router  fcr02a.hou02.softlayer.com
firewall        No
subnets         id          1194237
                identifier  192.168.0.160
                netmask     255.255.255.224
                gateway     192.168.0.161
                type        ADDITIONAL_PRIMARY
                usable ips  29
                id          816216
                identifier  172.16.0.168
                netmask     255.255.255.248
                gateway     172.16.0.169
                type        PRIMARY
                usable ips  5
                id          1139555
                identifier  2607:f0d0:1202:0147:0000:0000:0000:0000
                netmask     ffff:ffff:ffff:ffff:0000:0000:0000:0000
                gateway     2607:f0d0:1202:0147:0000:0000:0000:0001
                type        PRIMARY_6
                usable ips  -1
vs              tunneltest  tinylab.info  192.168.0.170  10.77.147.161
hardware        ceph2  tinylayer.net  172.16.0.170  10.77.176.9
```

### Actual Behavior
This fails in 5.0 
```
$ slcli --format raw vlan detail 1072493
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/vlan/detail.py", line 42, in cli
    for subnet in vlan['subnets']:
KeyError: 'subnets'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

```

### Environment Information
Operating System:  OS X 10.11.4 (15E65)
      Kernel Version: Darwin 15.4.0
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.0.0

**Comment by sudorandom** [comment] 2016-04-01 16:14
@greyhoundforty duplicate of #711. This should be fixed in master, (you can install from source using the instructions linked from #711).

**Closed by sudorandom** 2016-04-01 16:14 UTC
