### ISSUE TITLE
can not get details about vlan

### ISSUE THREAD

**Issue by jbd214** [softlayer/softlayer-python#720] opened 2016-04-21 17:37 UTC
### Expected Behavior
details about a vlan 
### Actual Behavior

C:\repos\PerfKitBenchmarker>slcli vlan detail 748272
An unexpected error has occured:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\SoftLayer\CLI\core.py", line 163, in main
    cli.main(**kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\SoftLayer\CLI\vlan\detail.py", line 42, in cli
    for subnet in vlan['subnets']:
KeyError: 'subnets'
### Environment Information
Operating System: Windows
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.0.1

**Comment by sudorandom** [comment] 2016-04-21 18:27
This is a duplicate of #716, #711 and #713. The fix will be released in with the next release. For now, you can follow the instructions here as a work-around: https://github.com/softlayer/softlayer-python/issues/711#issuecomment-203978557.

**Closed by sudorandom** 2016-04-21 18:27 UTC
