### ISSUE TITLE
API request: change block storage IQN via slcli

### ISSUE THREAD

**Issue by houstar** [softlayer/softlayer-python#826] opened 2017-06-03 05:38 UTC
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
slcli block access-list [volume-id]

We need slcli hardware access-edit --iqn [new_iqn_name] --password [new_password] [hardware_id]

At lease we have to specify one parameter in iqn or password.
More preciously, I expect that we can change the username of `slcli block access-list 24108495`

### Actual Behavior
No slcli block access-edit command
### Environment Information
Operating System:
Linux (RedHat 7.1)
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.6

**Comment by houstar** [comment] 2017-06-07 04:31
Hi @allmightyspiff, for speedup our development in this new feature, I have attach the API in the below.

#!/usr/local/bin/python
import SoftLayer

USERNAME="set me"
APIKEY="set me"

#In case you want to change the IQN from a bare metal set the baremetal id
bareMetalId = 'set me'
#In case you want to change the IQN from a virtual guest set the virtual guest
id
#virtualGuestId = 'set me'
#Set the block storage id
#NetworkStorage = 'set me'



client = SoftLayer.create_client_from_env(
        username=USERNAME,
        api_key=APIKEY
        )

#For bare metal server use the 'SoftLayer_Hardware_Server' service
resultAllowedHost = client['SoftLayer_Hardware_Server'].getAllowedHost(id = bareMetalId)

#For virtual guests use the 'SoftLayer_Virtual_Guest' service
#resultAllowedHost = client['SoftLayer_Virtual_Guest'].getAllowedHost(id = virtualGuestId)

# Changing the IQN passwod
resultChangePass=client['SoftLayer_Network_Storage_Allowed_Host'].setCredentialPassword("new_password", id = resultAllowedHost['id'])

# Changing the IQN name
resultEdit=client['SoftLayer_Network_Storage_Allowed_Host'].editObject({'name':'new_iqn_name'}, id = resultAllowedHost['id'])

print (resultChangePass)
print (resultEdit)

**Comment by houstar** [comment] 2017-06-07 04:40
lenos-mbp:~ leno$ python change_iqn.py
Traceback (most recent call last):
  File "change_iqn.py", line 32, in <module>
    resultEdit=client['SoftLayer_Network_Storage_Allowed_Host'].editObject({'name':'new_iqn_name'}, id = resultAllowedHost['id'])
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 195, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Unable to edit the object.  Please contact the system administrator.

**Comment by allmightyspiff** [comment] 2017-07-14 20:30
#841 will let you change the password once merged
#840 will let you change the LUN id.

Currently it doesn't seem possible to change the IQN name from the SoftLayer API however.

**Comment by houstar** [comment] 2017-08-02 02:30
Thanks allmightyspiff enriched the SLCLI ability to operate storage related.

We tried to use Softlayer API to change block storage IQN, sometimes succeed. sometimes failed.
Could you investigate more about thins since we really need this functionality?

**Comment by houstar** [comment] 2017-08-02 08:46
client['SoftLayer_Network_Storage_Allowed_Host'].editObject({'name':' new_iqn_name'}, id = allowed_host_id)

**Comment by allmightyspiff** [comment] 2020-07-07 20:32
Sorry for not following up on this until now. If this is still something you care about (after waiting 3 years) feel free to re-open this.

Currently I'm not able to reproduce this, but since you mention it only fails sometimes, that isn't too surprising.  If there is a recent failure, I should be able to look it up in our logs and try to open a bug report internally, as I don't think its a problem with the SLCLI client. I'd need to know the full API call (minus api keys).


```
$ slcli -vvv  call-api SoftLayer_Network_Storage_Allowed_Host editObject '{"name":"iqn.2020-07.cgallo-testcom:howdy"}' --id=1983916
Calling: SoftLayer_Network_Storage_Allowed_Host::editObject(id=1983916, mask='', filter='{}', args=({'name': 'iqn.2020-07.cgallo-testcom:howdy'},), limit=None, offset=None))
Starting new HTTPS connection (1): api.softlayer.com:443
https://api.softlayer.com:443 "POST /rest/v3.1/SoftLayer_Network_Storage_Allowed_Host/1983916/editObject.json HTTP/1.1" 200 4
Returned Data:
True
True
execution_time    0.659252s
api_calls         SoftLayer_Network_Storage_Allowed_Host::editObject (0.638244s)
version           softlayer-python/v5.8.9
python_version    3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
library_location  c:\users\allmi\source\py37\lib\site-packages\SoftLayer
id      1983916
mask
filter  {}
limit   None
offset  None
curl -u $SL_USER:$SL_APIKEY -X POST -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress" -d '{"parameters": [{"name": "iqn.2020-07.cgallo-testcom:howdy"}]}' 'https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage_Allowed_Host/1983916/editObject.json'
```

```
$ slcli --format=table call-api SoftLayer_Hardware_Server getObject --id=1901518 --mask="mask[id,hostname,allowedHost[id,name],activeTransactions]"
:....................:.............................................:
:               name : value                                       :
:....................:.............................................:
:           hostname : cgallo-test                                 :
:                 id : 1901518                                     :
:        allowedHost : :......:..................................: :
:                    : : name : value                            : :
:                    : :......:..................................: :
:                    : :   id : 1983916                          : :
:                    : : name : iqn.2020-07.cgallo-testcom:howdy : :
:                    : :......:..................................: :
: activeTransactions :                                             :
:....................:.............................................:
```

**Closed by allmightyspiff** 2020-07-07 20:32 UTC
Labels: New Feature
