### ISSUE TITLE
Unable to grab VLAN details.

### ISSUE THREAD

**Issue by CullenTaylor** [softlayer/softlayer-python#716] opened 2016-04-06 18:52 UTC
### Expected Behavior
```
$ slcli vlan detail <7-digit unique VLAN id>
...details...
```

### Actual Behavior
```
$ slcli vlan detail <7-digit unique VLAN id>
An unexpected error has occured:
Traceback (most recent call last):
  File "/root/env/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/root/env/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/root/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/root/env/lib/python2.7/site-packages/SoftLayer/CLI/vlan/detail.py", line 42, in cli
    for subnet in vlan['subnets']:
KeyError: 'subnets'
```

### Environment Information
Operating System: CentOS 7
softlayer-python version (`slcli --version`): 5.0.1

**Comment by sudorandom** [comment] 2016-04-13 14:47
This is a duplicate of #711 and #713

**Closed by sudorandom** 2016-04-13 14:47 UTC
