### ISSUE TITLE
feature request - secondary private ip api

### ISSUE THREAD

**Issue by kbroughton** [softlayer/softlayer-python#628] opened 2015-10-05 12:09 UTC
It appears that secondary private ips are possible, but cannot be automated at the moment.

Secondary IP addresses require ARIN justification through the available online form.  from http://knowledgelayer.softlayer.com/faqs/204

**Comment by underscorephil** [comment] 2015-10-16 19:53
It should be possible, at least as an addon to a VM order: http://sldn.softlayer.com/blog/phil/End-Nigh. If its possible without a VM the price ID will be in package 0.

**Comment by sudorandom** [comment] 2015-11-21 00:21
It's possible to create a new portable private subnet in batches of 8, 16 and 32 via `slcli subnet create private 8 [vlan-id]`.

The code to do this lives in `SoftLayer/managers/network.py` in the method `NetworkManager.add_subnet`.

**Comment by kbroughton** [comment] 2015-11-21 01:19
@underscorephil thanks, i didn't notice your comment till now.
I understand that the api exists to create subnets.  I don't understand how to assign a private ip from a given subnet to a host.

in amazon my steps are
$ aws ec2 describe-instances
-- retrieve $instance_id
$ aws ec2 create-vpc
vpc-23409801

$ aws ec2 create-subnet --vpc-id vpc-23409801
subnet-12391092

Attach private ip to ec2 instance.  THIS IS THE PIECE I"M LOOKING FOR
aws ec2 assign-private-ip-addresses  --network-interface-id $instance_id

NAME
             create-subnet
DESCRIPTION
       Creates a subnet in an existing VPC.

       When  you create each subnet, you provide the VPC ID and the CIDR block
       you want for the subnet. After you create a subnet,  you  can't  change
       its  CIDR  block.  The subnet's CIDR block can be the same as the VPC's
       CIDR block (assuming you want only a single subnet in the  VPC),  or  a
       subset of the VPC's CIDR block. If you create more than one subnet in a
       VPC, the subnets' CIDR blocks must not  overlap.  The  smallest  subnet
       (and  VPC) you can create uses a /28 netmask (16 IP addresses), and the
       largest uses a /16 netmask (65,536 IP addresses).


NAME
       assign-private-ip-addresses -

DESCRIPTION
       Assigns  one  or  more  secondary private IP addresses to the specified
       network interface. You can specify one or more  specific  secondary  IP
       addresses,  or  you can specify the number of secondary IP addresses to
       be automatically assigned within the subnet's  CIDR  block  range.  The
       number  of  secondary  IP  addresses that you can assign to an instance
       varies by instance type. For  information  about  instance  types,  see
       Instance  Types  in  the  Amazon Elastic Compute Cloud User Guide . For
       more information about Elastic IP addresses, see Elastic  IP  Addresses
       in the Amazon Elastic Compute Cloud User Guide .

       assign-private-ip-addresses is available only in EC2-VPC.

**Comment by sudorandom** [comment] 2015-11-21 01:40
With portable IP blocks ordered while specifying a VLAN, there is no additional assignment other than the configuration on the server. As long as the virtual server is in the same private VLAN then all you need to do is configure an interface with that IP address. How to do that is OS-specific.

See: http://knowledgelayer.softlayer.com/faqs/20 and http://knowledgelayer.softlayer.com/articles/static-and-portable-ip-blocks (at the very bottom)

@underscorephil, @allmightyspiff: Please check me on this.

**Comment by kbroughton** [comment] 2015-11-21 17:24
I can confirm that as long as I attach the ip from the appropriate Secondary On Vlan subnet to an interface on my vm i can ssh to the box using the secondary ip.

I'm guessing that assign-private-ip-addresses and the corresponding "release" command allow for managing the free ip pool.  My concern is that for automation, without a corresponding command for SL, I will have to write something based on nmap which can be very slow, to identify which ips in the subnet are available.

Eg. of attaching the same ip to two different servers.  No errors are thrown.
server1$ ifconfig eth0:2 10.146.51.132  netmask 255.255.255.192 up
server2$ ifconfig eth0:2 10.146.51.132  netmask 255.255.255.192 up

scp ~/myfile root@10.146.51.132:~/ 
myfile shows up on server1

server1$ ifconfig eth0:2 10.146.51.132  netmask 255.255.255.192 down
scp ~/myfile root@10.146.51.132:~/ 
myfile shows up on server2

So the fact that the ip pool is not managed could mean lots of strange results.

My use case is to automate the following steps
1. Create a subnet
2. Create 5 servers 3 additional ips each from the subnet to be attached as virtual ips.
3. Destroy and repeat

I do this very often while developing automation.  Perhaps you can suggest a better way to do this, but it seems to me that managing available ips in the subnet should be part of the API for subnet.py as it is for openstack and aws.

**Comment by sudorandom** [comment] 2015-11-21 17:41
Thanks for the detailed use-case. We'll see what possibilities exist. I think @underscorephil is the best person to take point on this.

**Comment by andy-swanson** [comment] 2015-11-28 00:55
Just wanted to make a comment as I am looking to do something similar and could not find anything exposed. (Coming from aws as well) Initially I was thinking I could work around this by using metadata puppet stores to understand ips that are in use by a given node. (Since we use puppet already) 

The problem is that I dont see how you can avoid a new instance coming up and trying to use an ip that I already am using as a secondary on another virtual server since there is no awareness of what is in use with a manual addition at the os layer. This is why aws lets you do whatever you need but you need to explicitly bind/unbind and can track everythung via api calls. Having ability to mark an ip as used or "bound" to a node and basically more control over blocks that you have is a huge help for lots of reasons. This allows all kinds of advanced use cases.

So anyway hust wanted to chime in and say I am looking for same functionality and am in process of building/automating a good size infrastructure across multiple sites in softlayer...

Regards
Andy

**Comment by benlake** [comment] 2015-12-07 04:14
@kbroughton @andy-swanson AWS and OpenStack tend to NAT everything, and thus have to do additional configuration beyond the creation of the subnet. That is why you have to be explicit about what IP address you're "attaching" to an instance. However, due to that requirement, they already have the tracking in place to provide you some validation concerning your IP address usage.

@kbroughton I find it interesting that your steps include "pick an IP [address]". If you're in a position to pick, then you know what's in use. I'll assume you don't pick and simply ask AWS for N IP addresses.

I agree it is handy to ask the cloud provider for another IP address, and just end up with one. However, with any deployment automation, you generally know and have to track what it is that is being deployed. So it is a matter of using relative information to solve the separation of desire (an IP address) and outcome (a specific IP address). For instance, if I know I'm deploying 5 instances and want them all to have an additional IP address out of the same subnet; I already know I want a subnet with at least 5 available IP addresses (e.g. /29), and for each instance I simply need to assign an offset during deployment (e.g. 1-5). Then subnet network identifier + 1 (gateway) + offset = IP address to configure on the instance; whatever that my be. Then you're deployment is described accurately and reproducible no matter what features could have been offloaded.

I wouldn't say this use case is specific to the python bindings, but since the forums are shut down, I'm not entirely sure where the best place to make feature requests of SoftLayer would be.

**Comment by kbroughton** [comment] 2015-12-07 04:37
@benlake 

There was a comment below the "Pick an IP address":
If you don't pass --private-ip-addresses you will get one assigned from the subnet the interface is attached to.

I've updated the comment to emphasize the desire to have free ips from the pool automatically offered.

"This is the use case i need most often:
aws ec2 assign-private-ip-addresses  --network-interface-id $interface_id --secondary-private-ip-address-count 4"

I've come across some blogs stating that softlayer users put comments in the notes in the UI of their secondary ips stating which hosts they are assigned to.  This is error prone and not suitable for my case where I create and destroy 5 clusters a day in automated test development.
If i have to pre-assign ips, that means i have to manually intervene and touch a config file each run.

Worst of all, if i make a mistake there will be no warning.  I'll just have some crazy network bugs because i've accidentally assigned the same ip to two different instances.  

If i want to know for sure that my secondary ip is free (and i can only hope it isn't assigned to an instanced that is temporarily powered off) then i have to do a portscan with nmap.  I don't know about softlayer, but with aws, even within your own private vpc, this requires a security variance request approved by Amazon.

"you generally know and have to track what it is that is being deployed"
This is not the case for me with aws.  I can just ask for n of the things i need.  Then when i want to modify a specific secondary private ip i just get the ip from ansible looping over the secondaries. 
{% for item in ansible_all_ipv4_addresses %}
{% if not primary_address %}
item['ipv4']['address']      (do something with this, like add it to /etc/network/interfaces )    
{% endif %}
{% endfor %}

I don't need to manage a frail config file at all.  I can easily and confidently scale the config-free approach to hundreds or thousands of instances.

**Comment by underscorephil** [comment] 2015-12-07 16:57
Howdy!

This request is a bit out of scope for this project. softlayer-python relies on the SLAPI as its datastore and to support this properly we would need to see some change in the underlying SLAPI/product offering. I will get a feature request in our internal tracking system so it can be properly evaluated and reference this thread.

**Comment by kbroughton** [comment] 2015-12-09 22:48
thanks!  Please do get us the ref so we can track it.

**Comment by allmightyspiff** [comment] 2015-12-11 22:08
I've created an internal issue to add this feature, however there is no ETA. In the mean time, IP notes are going to be your best solution at the SoftLayer level. I have created a small example of how to manage those which I hope you find useful.


[Edit Ip Notes](https://softlayer.github.io/python/edit_ip_note/)

**Closed** 2016-04-24 04:15 UTC
Labels: API, Unconfirmed
