### ISSUE TITLE
Throw error when run slcli image list |grep filename

### ISSUE THREAD

**Issue by cuiliquan** [softlayer/softlayer-python#761] opened 2016-08-22 03:06 UTC
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/image/list.py", line 58, in cli
    env.fout(table)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/environment.py", line 56, in fout
    self.out(self.fmt(output), newline=newline)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/environment.py", line 51, in fmt
    return formatting.format_output(output, fmt=self.format)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/formatting.py", line 39, in format_output
    return str(format_no_tty(data))
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 240, in __str__
    return self.__unicode__().encode(self.encoding)
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 243, in __unicode__
    return self.get_string()
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 987, in get_string
    formatted_rows = self._format_rows(rows, options)
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 942, in _format_rows
    return [self._format_row(row, options) for row in rows]
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 939, in _format_row
    return [self._format_value(field, value) for (field, value) in zip(self._field_names, row)]
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 890, in _format_value
    return self._unicode(value)
  File "/usr/lib/python2.7/site-packages/prettytable.py", line 179, in _unicode
    value = str(value)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/formatting.py", line 326, in __str__
    return str(self.original)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by sudorandom** [comment] 2016-08-22 03:54
It looks like this is a duplicate of https://github.com/softlayer/softlayer-python/issues/739. It is not released yet, but will be when v5.2.0 is released (https://github.com/softlayer/softlayer-python/milestone/13). In the meantime, can you verify that the issue is fixed for you in master? You can install the current code in master by following these instructions: http://softlayer-python.readthedocs.io/en/latest/install.html#from-source

**Comment by sudorandom** [comment] 2016-08-23 17:47
Closing this issue, as it's resolved in master. Let me know if this is still an issue after you follow the instructions in my previous comment.

**Closed by sudorandom** 2016-08-23 17:47 UTC
